png("plot3.png", width = 480, height = 480)
par(mar = c(5,5,4,4))
target <- household_power_consumption[household_power_consumption$Date == '1/2/2007' | household_power_consumption$Date == '2/2/2007',]
target <- transform(target, Sub_metering_1 = as.numeric(as.character(Sub_metering_1)))
target <- transform(target, Sub_metering_2 = as.numeric(as.character(Sub_metering_2)))
target <- transform(target, Sub_metering_3 = as.numeric(as.character(Sub_metering_3)))
target$DateTime <- strptime(paste(target$Date, target$Time, sep = ' '), format = "%d/%m/%Y %H:%M:%S")
plot(target$DateTime, target$Sub_metering_1, type = 'l', ylab = 'Energy sub metering', xlab = '')
points(target$DateTime, target$Sub_metering_2, type = 'l', col = 'red')
points(target$DateTime, target$Sub_metering_3, type = 'l', col= 'blue')
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col = c('black', 'red', 'blue'), lty = c(1, 1, 1))
dev.off()